### ISSUE TITLE
Split binary-studio-academy-bsa18 into 2 separate topics

### ISSUE THREAD

**Issue by volodymyr-kushnir** [senttor/homepage#16]
Привіт. Розріж, будь ласка, **binary-studio-academy-bsa18** на **binary-studio-academy** і **bsa18**. Зараз цей тег викидає репозиторій в сторону, а я б хотів, щоб всі разом були https://github.com/search?q=bsa18&type=Topics

**Comment by senttor** [comment]
Привіт. Так, звичайно.
